pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
    url(r'^events/overview/$', views.scheduled_event_overview, name='scheduled_event_overview'),
    url(r'^event/(?P<slug>.*)/$', views.scheduled_event, name='scheduled_event'),
    url(r'startuprow/apply/$', views.startuprow_apply, name='startuprow_apply'),
    url(r'community/roomsharing/$', views.room_sharing, name='room_sharing'),
    url(r'community/roomsharing/offer/$', views.room_sharing_offer, name='room_sharing_offer'),
    url(r'community/roomsharing/request/$', views.room_sharing_request, name='room_sharing_request'),
    url(r'community/roomsharing/offer/withdraw/$', views.withdraw_room_sharing_offer, name='withdraw_room_sharing_offer'),
    url(r'community/roomsharing/request/withdraw/$', views.withdraw_room_sharing_request, name='withdraw_room_sharing_request'),
    url(r'schedule/edusummits/mini-sprints/$', views.edu_summit_mini_sprints, name="edu_summit_mini_sprints"),
    url(r'secure_submission/$', views.secure_submission, name="secure_submission"),
    url(r'secure_submission/(?P<secure_submission_id>.*)/$', views.secure_submission_file_retrieval, name="secure_submission_file_retrieval"),
)

pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer

from pycon_project.views import creole_preview


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", redirect_to, {"url": "/%s/"  % settings.PYCON_YEAR}),
    url(r"^%s/" % settings.PYCON_YEAR, include(patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        
        url(r"^blog/", include("biblion.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^mailout/", include("mailout.urls")),
        
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", creole_preview, name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        
        # Symposion Apps
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),

        url(r"^schedule/", include("symposion.schedule.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),
        url(r"^venue/hotels/", direct_to_template, {"template": "venue/hotels.html"}, name="hotels"),
        
        url(r"^registration/", include("registration.urls")),
        url(r"^boxes/", include("boxes.urls")),
        
        url(r"^", include("wakawaka.urls")),
    ))),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
        url(r"", include("staticfiles.urls")),
    )

symposion/reviews/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns("symposion.reviews.views",
    url(r"^section/(?P<section_slug>[\w\-]+)/$", "review_section", name="review_section"),
    url(r"^section/(?P<section_slug>[\w\-]+)/assignments/$", "review_section", {"assigned": True}, name="review_section_assignments"),
    url(r"^section/(?P<section_slug>[\w\-]+)/status/$", "review_status", name="review_status"),
    url(r"^section/(?P<section_slug>[\w\-]+)/status/(?P<key>\w+)/$", "review_status", name="review_status"),
    url(r"^section/(?P<section_slug>[\w\-]+)/list/(?P<user_pk>\d+)/$", "review_list", name="review_list_user"),
    url(r"^section/(?P<section_slug>[\w\-]+)/admin/$", "review_admin", name="review_admin"),
    url(r"^section/(?P<section_slug>[\w\-]+)/admin/accept/$", "review_bulk_accept", name="review_bulk_accept"),
    url(r"^section/(?P<section_slug>[\w\-]+)/notification/(?P<status>\w+)/$", "result_notification", name="result_notification"),
    url(r"^section/(?P<section_slug>[\w\-]+)/notification/(?P<status>\w+)/prepare/$", "result_notification_prepare", name="result_notification_prepare"),
    url(r"^section/(?P<section_slug>[\w\-]+)/notification/(?P<status>\w+)/send/$", "result_notification_send", name="result_notification_send"),

    url(r"^review/(?P<pk>\d+)/$", "review_detail", name="review_detail"),

    url(r"^(?P<pk>\d+)/delete/$", "review_delete", name="review_delete"),
    url(r"^assignments/$", "review_assignments", name="review_assignments"),
    url(r"^assignment/(?P<pk>\d+)/opt-out/$", "review_assignment_opt_out", name="review_assignment_opt_out"),
)

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX, permanent=False)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",

        url(r"^sponsors/charityauction/$", RedirectView.as_view(
            url="/%s/events/auction/" % URL_PREFIX,
            permanent=True,
        )),

        # url(r"^$", RedirectView.as_view(
        #     url="/%s/sponsors/why-sponsor/" % URL_PREFIX,
        #     permanent=False,
        # )),
        # The real home page, currently shadowed:
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^mentorship/", include("pycon.mentorship.urls")),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "comps" in settings.INSTALLED_APPS:
    urlpatterns += patterns("", url(r"^", include("comps.urls")))

pycon_project/apps/boxes/models.py
from django.db import models
from django.template import Template, Context

from django.contrib.auth.models import User

import reversion

from markitup.fields import MarkupField


class Box(models.Model):
    
    label = models.CharField(max_length=100, db_index=True)
    content = MarkupField()
    
    created_by = models.ForeignKey(User, related_name="boxes")
    last_updated_by = models.ForeignKey(User, related_name="updated_boxes")
    
    def __unicode__(self):
        return self.label
    
    class Meta:
        verbose_name_plural = "boxes"
    
    def render(self):
        """
        Render the template data through the Django templating engine.
        """
        if hasattr(self, "_rendered_content"):
            return self._rendered_content
        t = Template(self.content)
        ctx = Context({})
        self._rendered_content = t.render(ctx)
        return self._rendered_content


reversion.register(Box)

pycon_project/apps/symposion/proposals/models.py
import datetime

from django.db import models

from markitup.fields import MarkupField

from symposion.conference.models import PresentationKind, PresentationCategory


class Proposal(models.Model):
    
    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    
    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
    ]

    DURATION_CHOICES = [
        (0, "No preference"),
        (1, "I prefer a 30 minute slot"),
        (2, "I prefer a 45 minute slot"),
    ]
    
    title = models.CharField(max_length=100)
    description = models.TextField(
        max_length = 400, # @@@ need to enforce 400 in UI
        help_text = "If your talk is accepted this will be made public and printed in the program. Should be one paragraph, maximum 400 characters."
    )
    kind = models.ForeignKey(PresentationKind)
    category = models.ForeignKey(PresentationCategory)
    abstract = MarkupField(
        help_text = "Detailed description and outline. Will be made public if your talk is accepted. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."
    )
    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)
    additional_notes = MarkupField(
        blank=True,
        help_text = "Anything else you'd like the program committee to know when making their selection: your past speaking experience, open source community experience, etc. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."
    )
    extreme = models.BooleanField(
        default=False,
        help_text = "'Extreme' talks are advanced talks with little or no introductory material. See <a href='http://us.pycon.org/2012/speaker/extreme/' target='_blank'>http://us.pycon.org/2012/speaker/extreme/</a> for details."
    )
    duration = models.IntegerField(choices=DURATION_CHOICES)
    submitted = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False,
    )
    speaker = models.ForeignKey("speakers.Speaker", related_name="proposals")
    additional_speakers = models.ManyToManyField("speakers.Speaker", blank=True)
    cancelled = models.BooleanField(default=False)
    
    def can_edit(self):
        return True
    
    @property
    def speaker_email(self):
        return self.speaker.email

    @property
    def number(self):
        return str(self.pk).zfill(3)
    
    def speakers(self):
        yield self.speaker
        for speaker in self.additional_speakers.all():
            yield speaker

pycon_project/apps/wiki/models.py
# stubbed

pycon_project/apps/boxes/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from boxes.models import Box


class BoxForm(forms.ModelForm):
    
    content = forms.CharField(widget=MarkItUpWidget())
    
    class Meta:
        model = Box
        fields = ["content"]

pycon_project/apps/symposion/proposals/forms.py
from django import forms
from django.db.models import Q

from markitup.widgets import MarkItUpWidget

from symposion.conference.models import PresentationKind, PresentationCategory
from symposion.proposals.models import Proposal


class ProposalForm(forms.ModelForm):
    
    class Meta:
        model = Proposal
        fields = [
            "title",
            "kind",
            "category",
            "audience_level",
            "extreme",
            "duration",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }
    
    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)
        self.fields["category"] = forms.ModelChoiceField(
            queryset = PresentationCategory.objects.order_by("name")
        )
    
    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class ProposalSubmitForm(ProposalForm):

    def __init__(self, *args, **kwargs):
        super(ProposalSubmitForm, self).__init__(*args, **kwargs)
        self.fields["kind"] = forms.ModelChoiceField(
            queryset = PresentationKind.available(),
            widget = forms.RadioSelect(),
            empty_label = None
        )


class ProposalEditForm(ProposalForm):
    
    class Meta:
        model = Proposal
        fields = [
            "title",
            "category",
            "audience_level",
            "extreme",
            "duration",
            "description",
            "abstract",
            "additional_notes",
        ]


class AddSpeakerForm(forms.Form):
    
    email = forms.EmailField(
        label = "Email address of new speaker (use their email address, not yours)"
    )
    
    def __init__(self, *args, **kwargs):
        self.proposal = kwargs.pop("proposal")
        super(AddSpeakerForm, self).__init__(*args, **kwargs)
    
    def clean_email(self):
        value = self.cleaned_data["email"]
        exists = self.proposal.additional_speakers.filter(
            Q(user=None, invite_email=value) |
            Q(user__email=value)
        ).exists()
        if exists:
            raise forms.ValidationError(
                "This email address has already been added to your talk proposal"
            )
        return value

pycon_project/apps/symposion/review/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from symposion.review.models import Review, Comment, ProposalMessage, VOTES


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["vote", "comment"]
        widgets = { "comment": MarkItUpWidget() }
    
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["vote"] = forms.ChoiceField(
            widget = forms.RadioSelect(),
            choices = VOTES.CHOICES
        )


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        widgets = { "text": MarkItUpWidget() }


class SpeakerCommentForm(forms.ModelForm):
    class Meta:
        model = ProposalMessage
        fields = ["message"]
        widgets = { "message": MarkItUpWidget() }


class BulkPresentationForm(forms.Form):
    talk_ids = forms.CharField(
        max_length=500,
        help_text="Provide a comma seperated list of talk ids to accept."
    )

pycon_project/templates/review/_review_table.html
{% comment %}
<div>
    <b>View</b>:
        <a href="#type-talk">Talks</a> |
        <a href="#type-panel">Panels</a> |
        <a href="#type-tutorial">Tutorials</a>
        <a href="#type-poster">Posters</a>
</div>
{% endcomment %}
<div class="badges legend mod">
    <div class="badge extreme">E</div><div class="label"> = EXTREME PyCon</div>
</div>

<hr />

<h3>Proposal Types: 
{% for type, props in proposals.iteritems %}
    <a href="#type-{{ type|slugify|lower }}">{{ type }}{{ props|length|pluralize }} ({{ props|length }})</a>{% if not forloop.last %}, {% endif %}
{% endfor %}
</h3>

{% for type, props in proposals.iteritems %}
    {% for proposal in props %}
        {% if forloop.first %}
            {% if proposal.kind.name %}
                <h2 id="type-{{ proposal.kind.name|slugify|lower }}">
                    {{ proposal.kind.name }}{{ props|length|pluralize }}
                </h2>
            {% endif %}
            <table class="review review-list">
                <thead>
                    <tr>
                        <th class="pr-number">
                            #
                        </th>
                        <th>
                            Title
                        </th>
                        <th>
                            Category
                        </th>
                        <th class="comments">
                            <span>Comments</span>
                        </td>
                        <th>
                            +1
                        </th>
                        <th>
                            +0
                        </th>
                        <th>
                            &minus;0
                        </th>
                        <th>
                            &minus;1
                        </th>
                        <th>
                            Rated
                        </th>
                        <th>
                            Result
                        </th>
                    </tr>
                <thead>
                <tbody>
        {% endif %}
        <tr class="{{ proposal.latest_vote }} {% if forloop.first %}first{% endif %}">
            <td class="pr-number">
                {{ proposal.number }}
            </td>
            <td class="pr-details">
                <div class="title">
                    <a href="{% url review_detail proposal.pk %}">{{ proposal.title }}</a>
                </div>
                <div class="metadata">
                    <span class="level {{ proposal.get_audience_level_display|lower }}">
                        {{ proposal.get_audience_level_display }}
                    </span>
                    {{ proposal.kind.name }}
                    <span class="author">by
                    <b>{{ proposal.speaker }}</b></span>
                    {% if proposal.additional_speakers.all %}
                        with
                        {{ proposal.additional_speakers.all|join:", " }}
                    {% endif %}
                    <div class="badges">
                        {% if proposal.extreme %}
                            <div class="badge extreme">E</div>
                        {% endif %}
                        {% if proposal.invited %}
                            <div class="badge invited">I</div>
                        {% endif %}
                    </div>
                </div>
                <div class="description" style="display:none">
                    <div>
                        {{ proposal.description }}
                    </div>
                    <div>
                        {{ proposal.abstract|safe }}
                    </div>
                </div>
            </td>
            <td>
                {{ proposal.category.name }}
            </td>
            <td class="count">
                {{ proposal.comment_count }}
            </td>
            <td class="count plus-one">
                {{ proposal.plus_one }}
            </td>
            <td class="count plus-zero">
                {{ proposal.plus_zero }}
            </td>
            <td class="count minus-zero">
                {{ proposal.minus_zero }}
            </td>
            <td class="count minus-one">
                {{ proposal.minus_one }}
            </td>
            <td class="count">
                {% if proposal in rated_proposals %}Yes{% else %}No{% endif %}
            </td>
            <td class="result {{ proposal.result.get_accepted_display }}">
                {{ proposal.result.get_accepted_display }}
            </td>
        </tr>
        {% if forloop.last %}
        </tbody>
            </table>
            <hr />
        {% endif %}
    {% endfor %}
{% empty %}
    <p>No matching proposals.</p>
{% endfor %}

pycon_project/templates/review/access_not_permitted.html
{% extends "review/base.html" %}

{% block subnav %}{% endblock %}

{% block primary %}
    <h1>Access Not Permitted</h1>
    
    <p>
        Sorry, you do not have permission to access this page. If you 
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

pycon_project/templates/review/review_assignment.html
{% extends "review/base.html" %}

{% block primary %}
    <h1>Review Assignments</h1>
    
    {% if assignments %}
        <table>
            <tr>
                <th>Proposal</th>
                <th>Opted out</th>
                <th>Opt out</th>
            </tr>
            {% for assignment in assignments %}
                <tr>
                    <td>
                        <a href="{% url review_detail assignment.proposal.pk %}">
                            {{ assignment.proposal.title }}
                        </a>
                    </td>
                    <td>
                        <form method="post" action="{% url review_assignment_opt_out assignment.pk %}">
                            {% csrf_token %}
                            <input type="submit" value="Opt-out" />
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>You do not have any assignments.</p>
    {% endif %}
{% endblock %}

pycon_project/templates/review/review_detail.html
{% extends "review/base.html" %}

{% load markitup_tags %}
{% load uni_form_tags %}

{% block primary %}

    <h1>Proposal Review</h1>

    <div class="proposal">

        <div class="result-box {{ proposal.result.get_accepted_display }} mod">
            <h2 class="proposal-title">#{{ proposal.number }}: {{ proposal.title }}</h2>
            <div class="result-content">
                <h6>Current status: <span>{{ proposal.result.get_accepted_display }}</span></h6>
            {% if is_reviewer_admin %}
                <form class="result-form" method="POST" action="">
                    {% csrf_token %}
                    {% if proposal.result.get_accepted_display == "accepted" %}
                        <input type="submit" name="result_submit" value="reject" class="reject" />
                        <input type="submit" name="result_submit" value="undecide" class="undecide" />
                    {% else %}
                        {% if proposal.result.get_accepted_display == "rejected" %}
                            <input type="submit" name="result_submit" value="accept" class="accept" />
                            <input type="submit" name="result_submit" value="undecide" class="undecide" />
                        {% else %}
                            <input type="submit" name="result_submit" value="accept" class="accept" />
                            <input type="submit" name="result_submit" value="reject" class="reject" />
                        {% endif %}
                    {% endif %}
                </form>
            {% endif %}

            </div>
        </div>

        <div class="badges">
            {% if proposal.extreme %}
                <div class="badge extreme">E</div>
            {% endif %}
            {% if proposal.invited %}
                <div class="badge invited">I</div>
            {% endif %}
        </div>

        {% if proposal.cancelled %}
            <p class="cancelled">Cancelled</p>
        {% endif %}

        <div>
            {{ proposal.description }}
        </div>

        <dl class="inline mod">
            <dt>Type:</dt>
            <dd>{{ proposal.kind.name }}</dd>

            <dt>Abstract:</dt>
            <dd>{{ proposal.abstract|safe }}</dd>

            <dt>Audience level:</dt>
            <dd>{{ proposal.get_audience_level_display }}</dd>

            <dt>Category:</dt>
            <dd>{{ proposal.category.name }}</dd>

            <dt>Duration:</dt>
            <dd>{{ proposal.get_duration_display }}</dd>

            <dt>Submitting speaker:</dt>
            <dd>{{ proposal.speaker }}</dd>

            <dt>About speaker:</dt>
            <dd>{{ proposal.speaker.biography|safe }}</dd>

            {% if proposal.additional_speakers.all %}
                <dt>Additional speakers:</dt>
                <dd>
                    <ul>
                    {% for speaker in proposal.additional_speakers.all %}
                        {% if speaker.user %}
                            <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
                        {% else %}
                            <li>{{ speaker.email }} &mdash; pending invitation</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </dd>
            {% endif %}

            {% if proposal.additional_notes %}
                <dt>Additional Notes:
                    <span>(private from submitter)</span>
                </dt>
                <dd class="additional_notes">
                    {{ proposal.additional_notes|safe }}
                </dd>
            {% endif %}

        </dl>

    </div>

    {% if is_reviewer_admin or not proposal.invited %}

        <h3>Votes</h3>

        <div class="votes-box {{ latest_vote.css_class }} mod">
            <div class="vote-count-box plus-one-box">
                <div class="label">+1 vote{{ proposal.plus_one|pluralize }}</div>
                <div class="number">{{ proposal.plus_one }}</div>
            </div>
            <div class="vote-count-box plus-zero-box">
                <div class="label">+0 vote{{ proposal.plus_zero|pluralize }}</div>
                <div class="number">{{ proposal.plus_zero }}</div>
            </div>
            <div class="vote-count-box minus-zero-box">
                <div class="label">&minus;0 vote{{ proposal.minus_zero|pluralize }}</div>
                <div class="number">{{ proposal.minus_zero }}</div>
            </div>
            <div class="vote-count-box minus-one-box">
                <div class="label">&minus;1 vote{{ proposal.minus_one|pluralize }}</div>
                <div class="number">{{ proposal.minus_one }}</div>
            </div>
            <div class="vote-count-box total">
                <div class="label"><b>responses</b></div>
                <div class="number"><b>{{ proposal.total_votes }}</b></div>
            </div>
        </div>

        {% if reviews %}
            <h3>Review Comments</h3>
            {% for review in reviews %}
                <div class="review-box">
                    <div class="vote">Vote: <b>{{ review.vote }}</b></div>
                    <div class="comment">{{ review.comment|safe }}</div>
                    <div class="dateline">
                        <b>{{ review.user }}</b> {{ review.submitted_at|timesince }} ago
                        {% if is_reviewer_admin %}<form method="POST" action="{% url review_delete review.pk %}" class="delete-comment">{% csrf_token %}<input type="submit" value="delete" /></form>{% endif %}
                    </div>
                </div>
                <div class="clear"></div>
            {% endfor %}
        {% endif %}

        <h3>Vote and Comment</h3>

        <p>Enter your vote and any comment to go along with it. You can revise your vote or comment multiple times with an existing vote (your previously recorded score will be replaced during calculations). <b>Your vote and comments are not public and will only be viewable by other reviewers.</b></p>

        {% markitup_media %}

        {% if review_form %}
            <form method="POST" action="" class="uniForm">
                {% csrf_token %}
                <fieldset>
                    {{ review_form|as_uni_form }}
                    <div class="form_block">
                        <input type="submit" name="vote_submit" value="submit" />
                    </div>
                </fieldset>
            </form>
        {% else %}
            <p>You do not have permission to vote on this proposal.</p>
        {% endif %}

        {% if proposal.messages.all %}
            <div class="spacer"></div>
            <h3>Conversation with Proposer</h3>
            {% for message in proposal.messages.all %}
                <div class="review-box">
                    <div class="comment">{{ message.message|safe }}</div>
                    <div class="dateline"><b>{{ message.user }}</b> {{ message.submitted_at|timesince }} ago</div>
                </div>
                <div class="clear"></div>
            {% endfor %}
        {% endif %}

        <div class="spacer"></div>
        <h3>Leave a Message</h3>

        <p>You can leave a message for the proposer, <b>who will be notified through email and given the chance to respond to your comments</b>.</p>

        <form action="" method="POST" class="uniForm" accept-charset="utf-8">
            {% csrf_token %}
            <fieldset>
                {{ message_form|as_uni_form }}
                <div class="form_block">
                    <input type="submit" name="message_submit" value="submit" />
                </div>
            </fieldset>
        </form>
        <div class="spacer"></div>
    {% endif %}
{% endblock %}