pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
    url(r'^events/overview/$', views.scheduled_event_overview, name='scheduled_event_overview'),
    url(r'^event/(?P<slug>.*)/$', views.scheduled_event, name='scheduled_event'),
    url(r'startuprow/apply/$', views.startuprow_apply, name='startuprow_apply'),
    url(r'community/roomsharing/$', views.room_sharing, name='room_sharing'),
    url(r'community/roomsharing/offer/$', views.room_sharing_offer, name='room_sharing_offer'),
    url(r'community/roomsharing/request/$', views.room_sharing_request, name='room_sharing_request'),
    url(r'community/roomsharing/offer/withdraw/$', views.withdraw_room_sharing_offer, name='withdraw_room_sharing_offer'),
    url(r'community/roomsharing/request/withdraw/$', views.withdraw_room_sharing_request, name='withdraw_room_sharing_request'),
    url(r'schedule/edusummits/mini-sprints/$', views.edu_summit_mini_sprints, name="edu_summit_mini_sprints"),
    url(r'secure_submission/$', views.secure_submission, name="secure_submission"),
    url(r'secure_submission/(?P<secure_submission_id>.*)/$', views.secure_submission_file_retrieval, name="secure_submission_file_retrieval"),
)

pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer

from pycon_project.views import creole_preview


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", redirect_to, {"url": "/%s/"  % settings.PYCON_YEAR}),
    url(r"^%s/" % settings.PYCON_YEAR, include(patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        
        url(r"^blog/", include("biblion.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^mailout/", include("mailout.urls")),
        
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", creole_preview, name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        
        # Symposion Apps
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),

        url(r"^schedule/", include("symposion.schedule.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),
        url(r"^venue/hotels/", direct_to_template, {"template": "venue/hotels.html"}, name="hotels"),
        
        url(r"^registration/", include("registration.urls")),
        url(r"^boxes/", include("boxes.urls")),
        
        url(r"^", include("wakawaka.urls")),
    ))),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
        url(r"", include("staticfiles.urls")),
    )

symposion/proposals/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns("symposion.proposals.views",
    url(r"^submit/$", "proposal_submit", name="proposal_submit"),
    url(r"^submit/([\w-]+)/$", "proposal_submit_kind", name="proposal_submit_kind"),
    url(r"^(\d+)/$", "proposal_detail", name="proposal_detail"),
    url(r"^(\d+)/edit/$", "proposal_edit", name="proposal_edit"),
    url(r"^(\d+)/submit_final/$", "proposal_submit_final", name="proposal_submit_final"),
    url(r"^(\d+)/speakers/$", "proposal_speaker_manage", name="proposal_speaker_manage"),
    url(r"^(\d+)/cancel/$", "proposal_cancel", name="proposal_cancel"),
    url(r"^(\d+)/leave/$", "proposal_leave", name="proposal_leave"),
    url(r"^(\d+)/join/$", "proposal_pending_join", name="proposal_pending_join"),
    url(r"^(\d+)/decline/$", "proposal_pending_decline", name="proposal_pending_decline"),
    
    url(r"^(\d+)/document/create/$", "document_create", name="proposal_document_create"),
    url(r"^document/(\d+)/delete/$", "document_delete", name="proposal_document_delete"),
    url(r"^document/(\d+)/([^/]+)$", "document_download", name="proposal_document_download"),
)

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX, permanent=False)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",

        url(r"^sponsors/charityauction/$", RedirectView.as_view(
            url="/%s/events/auction/" % URL_PREFIX,
            permanent=True,
        )),

        # url(r"^$", RedirectView.as_view(
        #     url="/%s/sponsors/why-sponsor/" % URL_PREFIX,
        #     permanent=False,
        # )),
        # The real home page, currently shadowed:
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^mentorship/", include("pycon.mentorship.urls")),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "comps" in settings.INSTALLED_APPS:
    urlpatterns += patterns("", url(r"^", include("comps.urls")))

pycon_project/apps/boxes/models.py
from django.db import models
from django.template import Template, Context

from django.contrib.auth.models import User

import reversion

from markitup.fields import MarkupField


class Box(models.Model):
    
    label = models.CharField(max_length=100, db_index=True)
    content = MarkupField()
    
    created_by = models.ForeignKey(User, related_name="boxes")
    last_updated_by = models.ForeignKey(User, related_name="updated_boxes")
    
    def __unicode__(self):
        return self.label
    
    class Meta:
        verbose_name_plural = "boxes"
    
    def render(self):
        """
        Render the template data through the Django templating engine.
        """
        if hasattr(self, "_rendered_content"):
            return self._rendered_content
        t = Template(self.content)
        ctx = Context({})
        self._rendered_content = t.render(ctx)
        return self._rendered_content


reversion.register(Box)

pycon_project/apps/symposion/proposals/models.py
import datetime

from django.db import models

from markitup.fields import MarkupField

from symposion.conference.models import PresentationKind, PresentationCategory


class Proposal(models.Model):
    
    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    
    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
    ]

    DURATION_CHOICES = [
        (0, "No preference"),
        (1, "I prefer a 30 minute slot"),
        (2, "I prefer a 45 minute slot"),
    ]
    
    title = models.CharField(max_length=100)
    description = models.TextField(
        max_length = 400, # @@@ need to enforce 400 in UI
        help_text = "If your talk is accepted this will be made public and printed in the program. Should be one paragraph, maximum 400 characters."
    )
    kind = models.ForeignKey(PresentationKind)
    category = models.ForeignKey(PresentationCategory)
    abstract = MarkupField(
        help_text = "Detailed description and outline. Will be made public if your talk is accepted. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."
    )
    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)
    additional_notes = MarkupField(
        blank=True,
        help_text = "Anything else you'd like the program committee to know when making their selection: your past speaking experience, open source community experience, etc. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."
    )
    extreme = models.BooleanField(
        default=False,
        help_text = "'Extreme' talks are advanced talks with little or no introductory material. See <a href='http://us.pycon.org/2012/speaker/extreme/' target='_blank'>http://us.pycon.org/2012/speaker/extreme/</a> for details."
    )
    duration = models.IntegerField(choices=DURATION_CHOICES)
    submitted = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False,
    )
    speaker = models.ForeignKey("speakers.Speaker", related_name="proposals")
    additional_speakers = models.ManyToManyField("speakers.Speaker", blank=True)
    cancelled = models.BooleanField(default=False)
    
    def can_edit(self):
        return True
    
    @property
    def speaker_email(self):
        return self.speaker.email

    @property
    def number(self):
        return str(self.pk).zfill(3)
    
    def speakers(self):
        yield self.speaker
        for speaker in self.additional_speakers.all():
            yield speaker

pycon_project/apps/wiki/models.py
# stubbed

pycon_project/apps/boxes/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from boxes.models import Box


class BoxForm(forms.ModelForm):
    
    content = forms.CharField(widget=MarkItUpWidget())
    
    class Meta:
        model = Box
        fields = ["content"]

pycon_project/apps/symposion/proposals/forms.py
from django import forms
from django.db.models import Q

from markitup.widgets import MarkItUpWidget

from symposion.conference.models import PresentationKind, PresentationCategory
from symposion.proposals.models import Proposal


class ProposalForm(forms.ModelForm):
    
    class Meta:
        model = Proposal
        fields = [
            "title",
            "kind",
            "category",
            "audience_level",
            "extreme",
            "duration",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }
    
    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)
        self.fields["category"] = forms.ModelChoiceField(
            queryset = PresentationCategory.objects.order_by("name")
        )
    
    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class ProposalSubmitForm(ProposalForm):

    def __init__(self, *args, **kwargs):
        super(ProposalSubmitForm, self).__init__(*args, **kwargs)
        self.fields["kind"] = forms.ModelChoiceField(
            queryset = PresentationKind.available(),
            widget = forms.RadioSelect(),
            empty_label = None
        )


class ProposalEditForm(ProposalForm):
    
    class Meta:
        model = Proposal
        fields = [
            "title",
            "category",
            "audience_level",
            "extreme",
            "duration",
            "description",
            "abstract",
            "additional_notes",
        ]


class AddSpeakerForm(forms.Form):
    
    email = forms.EmailField(
        label = "Email address of new speaker (use their email address, not yours)"
    )
    
    def __init__(self, *args, **kwargs):
        self.proposal = kwargs.pop("proposal")
        super(AddSpeakerForm, self).__init__(*args, **kwargs)
    
    def clean_email(self):
        value = self.cleaned_data["email"]
        exists = self.proposal.additional_speakers.filter(
            Q(user=None, invite_email=value) |
            Q(user__email=value)
        ).exists()
        if exists:
            raise forms.ValidationError(
                "This email address has already been added to your talk proposal"
            )
        return value

pycon_project/apps/symposion/review/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from symposion.review.models import Review, Comment, ProposalMessage, VOTES


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["vote", "comment"]
        widgets = { "comment": MarkItUpWidget() }
    
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["vote"] = forms.ChoiceField(
            widget = forms.RadioSelect(),
            choices = VOTES.CHOICES
        )


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        widgets = { "text": MarkItUpWidget() }


class SpeakerCommentForm(forms.ModelForm):
    class Meta:
        model = ProposalMessage
        fields = ["message"]
        widgets = { "message": MarkItUpWidget() }


class BulkPresentationForm(forms.Form):
    talk_ids = forms.CharField(
        max_length=500,
        help_text="Provide a comma seperated list of talk ids to accept."
    )

pycon_project/templates/proposals/base.html
{% extends "site_base.html" %}

{% block body_class %}full speaker{% endblock %}

{% block body %}
	<div class="span-24 main-content last">
        <h1 class="section-title">{% block subpage_title %}PyCon 2012 <span>Proposals</span>{% endblock %}</h1>
        {% block content %}{% endblock %}
    </div>
{% endblock body %}

pycon_project/templates/proposals/proposal_cancel.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>Cancel: {{ proposal.title }}</h1>
    
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <p>Are you sure you want to cancel <b>{{ proposal.title }}</b>?</p>
        <input type="submit" value="I am sure" />
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_detail.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>{{ proposal.title }}</h1>
    
    <p>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user %}
                <a href="{% url proposal_edit proposal.pk %}">Edit</a>
                | <a href="{% url proposal_cancel proposal.pk %}">Cancel</a>
            {% else %}
                <a href="{% url proposal_leave proposal.pk %}">Leave</a>
            {% endif %}
        {% else %}
            Cancelled
        {% endif %}
    </p>
    
    <div>
        {{ proposal.description }}
    </div>
    
    <p><b>Type</b>: {{ proposal.kind.name }}</p>
    
    <div>
        {{ proposal.abstract|safe }}
    </div>
    
    <p><b>Audience level</b>: {{ proposal.get_audience_level_display }}</p>
    
    <p><b>Submitting speaker</b>: {{ proposal.speaker }}</p>
    
    {% if proposal.additional_speakers.all %}
        <p><b>Additional speakers</b>:</p>
        <ul>
        {% for speaker in proposal.additional_speakers.all %}
            {% if speaker.user %}
                <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
            {% else %}
                <li>{{ speaker.email }} &mdash; pending invitation</li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}
    
    {% if request.user == proposal.speaker.user %}
        <p><b>Additional Notes:</b></p>
    
        <p>{{ proposal.additional_notes }}</p>
    {% endif %}
    
    <h2>Conversation with Reviewers</h2>
    
    {% for message in proposal.messages.all %}
        <div class="review-box">
            <div class="comment">{{ message.message|safe }}</div>
            <div class="dateline"><b>{{ message.user }}</b> {{ message.submitted_at|timesince }} ago</div>
        </div>
        <div class="clear"></div>
    {% endfor %}
    
    <h3>Leave a Message</h3>
    
    <p>You can leave a message for the reviewers here.</p>
    
    <form action="" method="POST" class="uniForm" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset>
            {{ message_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" name="message_submit" value="submit" />
            </div>
        </fieldset>
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_edit.html
{% extends "proposals/base.html" %}

{% load markitup_tags %}
{% load uni_form_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
    <style>
        .uniForm .formHint {
            width: 99%;
            line-height: 12pt;
            margin-top: 8px;
        }
        #div_id_extreme label {
            display: inline;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Edit: {{ proposal.title }}</h1>
    
    <p><a href="{% url proposal_speaker_manage proposal.pk %}">Manage speakers</a></p>
    
    {% markitup_media %}
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <fieldset>
            {{ form|as_uni_form }}
            <div class="form_block">
                <input type="submit" value="save" />
            </div>
        </fieldset>
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_error.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>{{ body }}</p>
{% endblock %}

pycon_project/templates/proposals/proposal_leave.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>Leave: {{ proposal.title }}</h1>
    
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <p>Are you sure you want to no longer speak on <b>{{ proposal.title }}</b>?</p>
        <input type="submit" value="I am sure" />
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_speaker_manage.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>Proposal: {{ proposal.title }}</h1>
    
    <p><a href="{% url proposal_edit proposal.pk %}">Edit proposal</a></p>
    
    <h2>Current Speakers</h2>
    
    {% for speaker in speakers %}
        {% if speaker.user %}
            <p><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</p>
        {% else %}
            <p>{{ speaker.email }} &mdash; pending invitation</p>
        {% endif %}
    {% endfor %}
    
    <h2>Add another speaker</h2>
    
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <fieldset>
            {{ add_speaker_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" value="add speaker" />
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
    $(function() {
        $("#id_email").focus();
    });
    </script>
{% endblock %}

pycon_project/templates/proposals/proposal_submit.html
{% extends "proposals/base.html" %}

{% load boxes_tags %}
{% load markitup_tags %}
{% load uni_form_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
    <style>
        .uniForm .formHint {
            line-height: 12pt;
            margin-top: 8px;
            width: 99%;
        }
        #div_id_kind ul li {
            display: inline;
        }
        #div_id_extreme label {
            display: inline;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/proposals.css" />
{% endblock %}


{% block content %}
    <h1>Submit A Proposal</h1>
    
    {% box "example_proposal" %}
    
    {% markitup_media %}
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <fieldset>
            {{ form|as_uni_form }}
            <div class="form_block">
                <p>
                    You will be able to edit your proposal after it has been submitted. The program committee may ask questions, provide feedback, and even suggest changes to your proposal as part of the review processes.
                </p>
                <input type="submit" name="finish" value="Save" />
                <!-- <span style="float: right; padding: 4px 6px">or</span> -->
                <input type="submit" name="add-speakers" value="Save and Add Additional Speakers" />
            </div>
        </fieldset>
    </form>
{% endblock %}