pycon/schedule/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns(
    "pycon.schedule.views",
    url(r"^sessions/staff.txt$", "session_staff_email", name="schedule_session_staff_email"),
    url(r"^sessions/$", "session_list", name="schedule_session_list"),
    url(r"^session/(\d+)/$", "session_detail", name="schedule_session_detail"),
    url(r"^session-staff.json", "session_staff_json", name="session_staff_json"),
    url(r"^slides_upload/(?P<presentation_id>[0-9,]+)/$", "slides_upload", name="pycon_schedule_slides_upload"),
    url(r"^slides_download/$", "slides_download", name="pycon_schedule_slides_download"),
)

pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
    url(r'^events/overview/$', views.scheduled_event_overview, name='scheduled_event_overview'),
    url(r'^event/(?P<slug>.*)/$', views.scheduled_event, name='scheduled_event'),
    url(r'startuprow/apply/$', views.startuprow_apply, name='startuprow_apply'),
    url(r'community/roomsharing/$', views.room_sharing, name='room_sharing'),
    url(r'community/roomsharing/offer/$', views.room_sharing_offer, name='room_sharing_offer'),
    url(r'community/roomsharing/request/$', views.room_sharing_request, name='room_sharing_request'),
    url(r'community/roomsharing/offer/withdraw/$', views.withdraw_room_sharing_offer, name='withdraw_room_sharing_offer'),
    url(r'community/roomsharing/request/withdraw/$', views.withdraw_room_sharing_request, name='withdraw_room_sharing_request'),
    url(r'schedule/edusummits/mini-sprints/$', views.edu_summit_mini_sprints, name="edu_summit_mini_sprints"),
    url(r'secure_submission/$', views.secure_submission, name="secure_submission"),
    url(r'secure_submission/(?P<secure_submission_id>.*)/$', views.secure_submission_file_retrieval, name="secure_submission_file_retrieval"),
)

pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer

from pycon_project.views import creole_preview


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", redirect_to, {"url": "/%s/"  % settings.PYCON_YEAR}),
    url(r"^%s/" % settings.PYCON_YEAR, include(patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        
        url(r"^blog/", include("biblion.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^mailout/", include("mailout.urls")),
        
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", creole_preview, name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        
        # Symposion Apps
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),

        url(r"^schedule/", include("symposion.schedule.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),
        url(r"^venue/hotels/", direct_to_template, {"template": "venue/hotels.html"}, name="hotels"),
        
        url(r"^registration/", include("registration.urls")),
        url(r"^boxes/", include("boxes.urls")),
        
        url(r"^", include("wakawaka.urls")),
    ))),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
        url(r"", include("staticfiles.urls")),
    )

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX, permanent=False)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",

        url(r"^sponsors/charityauction/$", RedirectView.as_view(
            url="/%s/events/auction/" % URL_PREFIX,
            permanent=True,
        )),

        # url(r"^$", RedirectView.as_view(
        #     url="/%s/sponsors/why-sponsor/" % URL_PREFIX,
        #     permanent=False,
        # )),
        # The real home page, currently shadowed:
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^mentorship/", include("pycon.mentorship.urls")),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "comps" in settings.INSTALLED_APPS:
    urlpatterns += patterns("", url(r"^", include("comps.urls")))

pycon/schedule/models.py
import os
from datetime import datetime

from django.db import models

from django.contrib.auth.models import User

from symposion.schedule.models import Day, Slot, Presentation


class Session(models.Model):

    day = models.ForeignKey(Day, related_name="sessions")
    slots = models.ManyToManyField(Slot, related_name="sessions")

    def sorted_slots(self):
        return self.slots.order_by("start")

    def start(self):
        slots = self.sorted_slots()
        if slots:
            return list(slots)[0].start
        else:
            return None

    def end(self):
        slots = self.sorted_slots()
        if slots:
            return list(slots)[-1].end
        else:
            return None

    def __unicode__(self):
        start = self.start()
        end = self.end()
        if start and end:
            return "{}: {} - {}".format(
                self.day, start.strftime('%X'), end.strftime('%X'))
        return ""

    @property
    def needs_volunteers(self):
        chair = SessionRole.objects.filter(session=self, role=SessionRole.SESSION_ROLE_CHAIR).exclude(status=False)
        runner = SessionRole.objects.filter(session=self, role=SessionRole.SESSION_ROLE_RUNNER).exclude(status=False)
        return not (chair and runner)

class SessionRole(models.Model):

    SESSION_ROLE_CHAIR = 1
    SESSION_ROLE_RUNNER = 2

    SESSION_ROLE_TYPES = [
        (SESSION_ROLE_CHAIR, "Session Chair"),
        (SESSION_ROLE_RUNNER, "Session Runner"),
    ]

    session = models.ForeignKey(Session)
    user = models.ForeignKey(User)
    role = models.IntegerField(choices=SESSION_ROLE_TYPES)
    status = models.NullBooleanField()

    submitted = models.DateTimeField(default=datetime.now)

    class Meta:
        unique_together = [("session", "user", "role")]

    def __unicode__(self):
        return u"%s %s: %s" % (self.user, self.session,
                               self.SESSION_ROLE_TYPES[self.role-1][1])


def get_presentation_upload_path(instance, filename):
    return os.path.join(
        "presentation_slides/{}/{}/{}".format(
            instance.presentation.id,
            datetime.now().isoformat(),
            filename
        )
    )


class SlidesUpload(models.Model):
    class Meta:
        permissions = (("can_download_slides", "Access and Download uploaded slides"),)

    presentation = models.ForeignKey(Presentation)
    slides = models.FileField(
        "PDF export of your slides",
        blank=False,
        null=False,
        upload_to=get_presentation_upload_path,
    )

    def filename(self):
        return os.path.basename(self.slides.name)

pycon/tutorials/models.py
import datetime

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from pycon.models import PyConTutorialProposal


class PyConTutorialMessage(models.Model):
    """Message attached to a tutorial."""
    tutorial = models.ForeignKey(PyConTutorialProposal,
                                 related_name="tutorial_messages")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             help_text=_(u"User who submitted the message"))
    message = models.TextField()
    submitted_at = models.DateTimeField(default=datetime.datetime.now,
                                        editable=False)

    class Meta:
        ordering = ["-submitted_at"]

    def __unicode__(self):
        return u"%s message submitted: %s" % (self.tutorial, self.submitted_at)

pycon_project/apps/boxes/models.py
from django.db import models
from django.template import Template, Context

from django.contrib.auth.models import User

import reversion

from markitup.fields import MarkupField


class Box(models.Model):
    
    label = models.CharField(max_length=100, db_index=True)
    content = MarkupField()
    
    created_by = models.ForeignKey(User, related_name="boxes")
    last_updated_by = models.ForeignKey(User, related_name="updated_boxes")
    
    def __unicode__(self):
        return self.label
    
    class Meta:
        verbose_name_plural = "boxes"
    
    def render(self):
        """
        Render the template data through the Django templating engine.
        """
        if hasattr(self, "_rendered_content"):
            return self._rendered_content
        t = Template(self.content)
        ctx = Context({})
        self._rendered_content = t.render(ctx)
        return self._rendered_content


reversion.register(Box)

pycon_project/apps/symposion/proposals/models.py
import datetime

from django.db import models

from markitup.fields import MarkupField

from symposion.conference.models import PresentationKind, PresentationCategory


class Proposal(models.Model):
    
    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    
    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
    ]

    DURATION_CHOICES = [
        (0, "No preference"),
        (1, "I prefer a 30 minute slot"),
        (2, "I prefer a 45 minute slot"),
    ]
    
    title = models.CharField(max_length=100)
    description = models.TextField(
        max_length = 400, # @@@ need to enforce 400 in UI
        help_text = "If your talk is accepted this will be made public and printed in the program. Should be one paragraph, maximum 400 characters."
    )
    kind = models.ForeignKey(PresentationKind)
    category = models.ForeignKey(PresentationCategory)
    abstract = MarkupField(
        help_text = "Detailed description and outline. Will be made public if your talk is accepted. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."
    )
    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)
    additional_notes = MarkupField(
        blank=True,
        help_text = "Anything else you'd like the program committee to know when making their selection: your past speaking experience, open source community experience, etc. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."
    )
    extreme = models.BooleanField(
        default=False,
        help_text = "'Extreme' talks are advanced talks with little or no introductory material. See <a href='http://us.pycon.org/2012/speaker/extreme/' target='_blank'>http://us.pycon.org/2012/speaker/extreme/</a> for details."
    )
    duration = models.IntegerField(choices=DURATION_CHOICES)
    submitted = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False,
    )
    speaker = models.ForeignKey("speakers.Speaker", related_name="proposals")
    additional_speakers = models.ManyToManyField("speakers.Speaker", blank=True)
    cancelled = models.BooleanField(default=False)
    
    def can_edit(self):
        return True
    
    @property
    def speaker_email(self):
        return self.speaker.email

    @property
    def number(self):
        return str(self.pk).zfill(3)
    
    def speakers(self):
        yield self.speaker
        for speaker in self.additional_speakers.all():
            yield speaker

pycon_project/apps/wiki/models.py
# stubbed

pycon/schedule/forms.py
from django import forms

from .models import SlidesUpload

class SlidesUploadForm(forms.ModelForm):

    class Meta:
        model = SlidesUpload
        fields = ["slides"]

pycon/tutorials/forms.py
from django import forms
from django.forms import Textarea

from markedit.widgets import MarkEdit

from pycon.tutorials.models import PyConTutorialMessage


class TutorialMessageForm(forms.ModelForm):
    class Meta:
        model = PyConTutorialMessage
        fields = [
            "message"
        ]
        widgets = {
            'message': MarkEdit(),
        }


class BulkEmailForm(forms.Form):
    subject = forms.CharField()
    body = forms.CharField(
        widget=Textarea(attrs={'class': 'fullwidth-textarea'})
    )

pycon_project/apps/boxes/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from boxes.models import Box


class BoxForm(forms.ModelForm):
    
    content = forms.CharField(widget=MarkItUpWidget())
    
    class Meta:
        model = Box
        fields = ["content"]

pycon_project/templates/schedule/_grid.html
<table>
    <tr>
        <th>&nbsp;</th>
        {% for track in day.tracks %}
            <th>{{ track.name }}</th>
        {% endfor %}
    </tr>
    {% for row in day %}
        <tr>
            <td class="time">{{ row.time|date:"h:iA" }}</td>
            {% for slot in row.slots %}
                <td colspan="{{ row.colspan }}" rowspan="{{ slot.rowspan }}" class="slot {{ slot.kind.name }} rowspan-{{ slot.rowspan }} colspan-{{ row.colspan }}">
                    {% if not slot.content %}
                        <span class="controls"><b>add</b>: <a href="{% url schedule_slot_add slot.pk "plenary" %}" rel="facebox">plenary</a> | <a href="{% url schedule_slot_add slot.pk "break" %}" rel="facebox">break</a> | <a href="{% url schedule_slot_add slot.pk "presentation" %}" rel="facebox">presentation</a> | <a href="{% url schedule_slot_add slot.pk "tutorial" %}" rel="facebox">tutorial</a></span>
                    {% else %}
                        {% if slot.kind.name == "recess" %}
                            <div class="title">{{ slot.content.title }}</div>
                        {% else %}
                            {% if slot.kind.name == "plenary" %}
                                <div class="title">{{ slot.content.title }}</div>
                                <div class="speaker">{{ slot.content.speaker }}</div>
                            {% else %}
                                <div class="title">{{ slot.content.title }}</div>
                                <div class="speaker">{{ slot.content.speaker }}</div>
                            {% endif %}
                        {% endif %}
                        <span class="controls"><b>actions</b>: {% if slot.content.kind.name != "Tutorial" %}<a href="{% url schedule_slot_edit slot.pk %}" rel="facebox">edit</a> | {% endif %}<a href="{% url schedule_slot_remove slot.pk %}" rel="facebox">remove</a></span>
                    {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>

pycon_project/templates/schedule/base.html
{% extends "site_base.html" %}

{% block body_class %}full schedule{% endblock %}

{% block subnav %}
{% endblock %}


{% block right %}{% endblock %}

pycon_project/templates/schedule/list_posters.html
{% extends "schedule/base.html" %}

{% load boxes_tags %}

{% block extra_head %}
    <style>
        .session {
            margin-top: 10px;
        }
        .title {
            font-size: 14pt;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Accepted Posters</h1>
    
    <div>
        {% box "posters-intro" %}
    </div>
    
    {% for poster in posters %}
        <div class="session">
            <div class="title">
                <a href="{% url schedule_presentation poster.pk %}">{{ poster.title }}</a>
            </div>
            <div class="metadata">
                {{ poster.get_audience_level_display }}
                {{ poster.get_session_type_display }}
                by
                {{ poster.speaker }}
                {% if poster.additional_speakers.all %}
                    with
                    {{ poster.additional_speakers.all|join:", " }}
                {% endif %}
            </div>
        </div>
    {% empty %}
        <p>No accepted posters yet.</p>
    {% endfor %}
    
{% endblock %}

pycon_project/templates/schedule/list_presentations.html
{% extends "schedule/base.html" %}

{% block extra_head %}
    <style>
        .session {
            margin-top: 10px;
        }
        .title {
            font-size: 14pt;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>{{ kind }}</h1>
    
    {% for talk in talks %}
        <div class="session">
            <div class="title">
                <a href="{% url schedule_presentation talk.pk %}">{{ talk.title }}</a>
            </div>
            <div class="metadata">
                {{ talk.get_audience_level_display }}
                {{ talk.kind.name }}
                by
                {{ talk.speaker }}
                {% if talk.additional_speakers.all %}
                    with
                    {{ talk.additional_speakers.all|join:", " }}
                {% endif %}
                <div class="badges">
                    {% if talk.extreme_pycon %}
                        <div class="badge extreme">E</div>
                    {% endif %}
                    <div class="clear"></div>
                </div>
                <div>
                    <p>{{ talk.description }}</p>
                </div>
            </div>
        </div>
        <hr />
    {% endfor %}
    
    <div class="badges legend">
        <div class="badge extreme">E</div><div class="label"> = EXTREME PyCon</div>
    </div>

{% endblock %}

pycon_project/templates/schedule/list_talks.html
{% extends "schedule/base.html" %}

{% block extra_head %}
    <style>
        .session {
            margin-top: 10px;
        }
        .title {
            font-size: 14pt;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Accepted Talks and Panels</h1>
    
    <div class="badges legend">
        <div class="badge extreme">E</div><div class="label"> = EXTREME PyCon</div>
        <div class="clear"></div>
        <div class="badge invited">I</div><div class="label"> = Invited</div>
    </div>
    
    {% for talk in talks %}
        <div class="session">
            <div class="title">
                <a href="{% url schedule_presentation talk.pk %}">{{ talk.title }}</a>
            </div>
            <div class="metadata">
                {{ talk.get_audience_level_display }}
                {{ talk.get_session_type_display }}
                by
                {{ talk.speaker }}
                {% if talk.additional_speakers.all %}
                    with
                    {{ talk.additional_speakers.all|join:", " }}
                {% endif %}
                <div class="badges">
                    {% if talk.extreme_pycon %}
                        <div class="badge extreme">E</div>
                    {% endif %}
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    {% empty %}
        <p>No accepted talks or panels yet.</p>
    {% endfor %}
    
{% endblock %}

pycon_project/templates/schedule/presentation_detail.html
{% extends "schedule/base.html" %}

{% load timezone_filters %}

{% block head_title %}Presentation: {{ presentation.title }}{% endblock %}

{% block extra_head %}
    <style>
        a.unbookmark {
            text-decoration: none;
            padding-left: 20px;
            background: url(/2011/site_media/static/img/star.png) no-repeat left;
        }
        a.bookmark {
            text-decoration: none;
            padding-left: 20px;
            background: url(/2011/site_media/static/img/star_unselected.png) no-repeat left;
        }
        div.slot {
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    
    <h1>{{ presentation.title }}</h1>

    <div class="badges">
        {% if presentation.extreme %}
            <div class="badge extreme">E</div>
        {% endif %}
    </div>

    {% if presentation.cancelled %}
        <p class="cancelled">Cancelled</p>
    {% endif %}

    <div class="speakers">
        {% for speaker in presentation.speakers %}
            <a href="{% url speaker_profile speaker.id %}">{{ speaker }}</a>
        {% if not forloop.last %}, {% endif %}{% endfor %}
    </div>
    
    <div class="badges">
        {% if presentation.extreme_pycon %}
            <div class="badge extreme">E</div>
        {% endif %}
        <div class="clear"></div>
    </div>

    <dl class="inline mod">
        <dt>Type:</dt>
        <dd>{{ presentation.kind.name }}</dd>

        <dt>Audience level:</dt>
        <dd>{{ presentation.get_audience_level_display }}</dd>

        <dt>Category:</dt>
        <dd>{{ presentation.category.name }}</dd>
    </dl>
    
    {% if presentation.slot %}
        <div class="slot">{{ presentation.slot.start|localtime:timezone|date:"F jS" }} {{ presentation.slot.start|localtime:timezone|date:"P" }} &ndash; {{ presentation.slot.end|localtime:timezone|date:"P" }}</div>
    {% endif %}

    <hr />

    <h3>Description</h3>

    <div class="description">{{ presentation.description }}</div>
    
    <hr />

    <h3>Abstract</h3>
    
    <div class="abstract">{{ presentation.abstract|safe }}</div>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("a.bookmark").live("click", function() {
                aElem = $(this);
                $.ajax({
                    type: "POST",
                    url: this.href,
                    data: "action=add;csrfmiddlewaretoken={{ csrf_token }}",
                    success: function() {
                        aElem.text("unbookmark");
                        aElem.removeClass("bookmark");
                        aElem.addClass("unbookmark");
                    },
                    error: function(xhr, options, error) {
                        alert(xhr.status);
                    }
                });
                return false;
            });
            $("a.unbookmark").live("click", function() {
                aElem = $(this);
                $.ajax({
                    type: "POST",
                    url: this.href,
                    data: "action=delete;csrfmiddlewaretoken={{ csrf_token }}",
                    success: function(response) {
                        aElem.text("bookmark");
                        aElem.removeClass("unbookmark");
                        aElem.addClass("bookmark");
                    },
                    error: function(xhr, options, error) {
                        alert(xhr.status);
                    }
                });
                return false;
            });
        });
    </script>
{% endblock %}

pycon_project/templates/schedule/session_list.html
{% extends "schedule/base.html" %}

{% block body %}
    <h1>Sessions</h1>
    
    <ul>
        {% for session in sessions %}
            {% if session.sorted_slots %}
                <li>
                    <a href="{% url schedule_session_detail session.pk %}">[{{ session.track }}] {{ session }}</a>
                    <ul>
                        {% for role in session.sessionrole_set.all %}
                            <li><b>{{ role.get_role_display }}: {{ role.user.get_full_name }} ({{ role.user }})</b></li>
                        {% empty %}
                            <li><b>No volunteers signed up</b></li>
                        {% endfor %}
                        {% for slot in session.sorted_slots %}
                            <li>{{ slot }}: {% if slot.content %}<a href="{% url schedule_presentation slot.content.pk %}">{{ slot.content }}</a>{% endif %}</li>
                        {% empty %}
                            <li>No slots in session.</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endif %}
        {% empty %}
            <li>No sessions defined.</li>
        {% endfor %}
    </ul>
    
{% endblock %}

pycon_project/templates/schedule/track_detail.html
{% extends "schedule/base.html" %}

{% block body %}
    
    <p><a href="{% url schedule_track_list %}">Tracks</a> &raquo;</p>
    
    <h1>Track: {{ track }}</h1>
    
    <h2>Sessions</h2>
    
    <ul>
        {% for session in track.sessions.all %}
            {% if session.sorted_slots %}
                <li>
                    <a href="{% url schedule_session_detail session.pk %}">[{{ session.track }}] {{ session }}</a>
                    <ul>
                        {% for role in session.sessionrole_set.all %}
                            <li><b>{{ role.get_role_display }}: {{ role.user }}</b></li>
                        {% empty %}
                            <li><b>No volunteers signed up</b></li>
                        {% endfor %}
                        {% for slot in session.sorted_slots %}
                            <li>{{ slot }}: {% if slot.content %}<a href="{% url schedule_presentation slot.content.pk %}">{{ slot.content }}</a>{% endif %}</li>
                        {% empty %}
                            <li>No slots in session.</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endif %}
        {% empty %}
            <li>No sessions in track.</li>
        {% endfor %}
    </ul>
    
{% endblock %}